In [45]:
import pandas as pd
import numpy as np

In [46]:
data=pd.read_csv('2.csv')

In [47]:
data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [48]:
data.shape

(13319, 9)

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13319 entries, 0 to 13318
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13319 non-null  object
 1   availability  13319 non-null  object
 2   location      13318 non-null  object
 3   size          13303 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13319 non-null  object
 6   bath          13245 non-null  float64
 7   balcony       12710 non-null  float64
 8   price         13319 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.6+ KB

In [50]:
for column in data.columns:
    print(data[column].value_counts())
    print("*"*20)

area_type
Super built-up  Area    8789
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
********************
availability
Ready To Move    10580
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
16-Oct               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
********************
location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64
********************
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          537
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64
********************
society
GrrvaGr    80
PrarePa    76
Prtates    59
Sryalan    59
GMown E    56
           ..
SNadeAr     1
DSellil     1
Shensit     1
VKvenas     1
Vemes H     1
Name: count, Length: 2688, dtype: int64
********************
total_sqft
1200           843
1100           221
1500           205
2400           196
600            180
              ...
2920             1
5665.84          1
1369             1
7150             1
1200 - 1470      1
Name: count, Length: 2117, dtype: int64
********************
bath
2.0     6908
3.0     3285
4.0     1226
1.0      787
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
27.0       1
14.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64
********************
balcony
2.0    5113
1.0    4896
3.0    1672
0.0    1029
Name: count, dtype: int64
********************
price
75.00    310
65.00    302
55.00    275
60.00    270
45.00    240
        ...
43.04      1
61.11      1
46.56      1
42.54      1
47.35      1
Name: count, Length: 1994, dtype: int64
********************

In [51]:
data.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5501
total_sqft         0
bath              74
balcony          609
price              0
dtype: int64

In [52]:
data.drop(columns=['area_type','availability','society','balcony'],inplace=True)

In [53]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13319 entries, 0 to 13318
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13318 non-null  object
 1   size        13303 non-null  object
 2   total_sqft  13319 non-null  object
 3   bath        13245 non-null  float64
 4   price       13319 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [54]:
data['location'].value_counts()

location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64

In [55]:
data['location']=data['location'].fillna('Sarjarpur Road')

In [56]:
data['size'].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          537
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [57]:
data['size']=data['size'].fillna('2 BHK')

In [58]:
data['bath']=data['bath'].fillna(data['bath'].median())

In [59]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13319 entries, 0 to 13318
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13319 non-null  object
 2   total_sqft  13319 non-null  object
 3   bath        13319 non-null  float64
 4   price       13319 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [60]:
data['bhk']=data['size'].str.split().str.get(0).astype(int)

In [61]:
data[data.bhk>20]

                       location        size total_sqft  bath  price  bhk
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [62]:
data['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(2117,), dtype=object)

In [63]:
def convertRange(x):
    temp=x.split('-')
    if len(temp)==2:
        return (float(temp[0])+ float(temp[1]))/2
    try:
        return float(x)
    except:
        return None

In [64]:
data['total_sqft']=data['total_sqft'].apply(convertRange)

In [65]:
data.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

In [66]:
data['price_per_sqft'] = data['price']*100000 / data['total_sqft']

In [67]:
data['price_per_sqft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13314     6530.612245
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
Name: price_per_sqft, Length: 13319, dtype: float64

In [68]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13273.000000  13319.000000  13319.000000  13319.000000    1.327300e+04
mean    1559.702760      2.688866    112.572802      2.802913    7.907864e+03
std     1238.420901      1.338735    148.974965      1.294450    1.064336e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.267458e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434783e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311828e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [69]:
data['location'].value_counts()

location
Whitefield                                      540
Sarjapur  Road                                  399
Electronic City                                 302
Kanakpura Road                                  273
Thanisandra                                     234
                                               ...
Maragondana Halli, kr puram, old madras road      1
Chikkajala                                        1
Udayagiri                                         1
pavitra paradise                                  1
Chikbasavanapura                                  1
Name: count, Length: 1306, dtype: int64

In [70]:
data['location'] = data['location'].apply(lambda x: x.strip())
location_count=data['location'].value_counts()

In [71]:
location_count

location
Whitefield                541
Sarjapur  Road            399
Electronic City           304
Kanakpura Road            273
Thanisandra               237
                         ...
Xavier Layout               1
Ramanagara Channapatna      1
Maheswari Nagar             1
Hsr layout sector3          1
Thyagraj Nagar              1
Name: count, Length: 1295, dtype: int64

In [72]:
location_count_less_10= location_count[location_count<=10]
location_count_less_10

location
1st Block Koramangala     10
Dairy Circle              10
Nagadevanahalli           10
Sadashiva Nagar           10
Naganathapura             10
                          ..
Xavier Layout              1
Ramanagara Channapatna     1
Maheswari Nagar            1
Hsr layout sector3         1
Thyagraj Nagar             1
Name: count, Length: 1054, dtype: int64

In [73]:
data['location']=data['location'].apply(lambda x: 'other' if x in location_count_less_10 else x)

In [74]:
data['location'].value_counts()

location
other                        2886
Whitefield                    541
Sarjapur  Road                399
Electronic City               304
Kanakpura Road                273
                             ...
Tindlu                         11
Marsur                         11
2nd Phase Judicial Layout      11
Thyagaraja Nagar               11
HAL 2nd Stage                  11
Name: count, Length: 242, dtype: int64

In [75]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13273.000000  13319.000000  13319.000000  13319.000000    1.327300e+04
mean    1559.702760      2.688866    112.572802      2.802913    7.907864e+03
std     1238.420901      1.338735    148.974965      1.294450    1.064336e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.267458e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434783e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311828e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [76]:
(data['total_sqft']/data['bhk']).describe()

count    13273.000000
mean       575.076768
std        388.219738
min          0.250000
25%        473.333333
50%        552.500000
75%        625.000000
max      26136.000000
dtype: float64

In [77]:
data = data[((data['total_sqft']/data['bhk'])>=300)]
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  12529.000000  12529.000000  12529.000000  12529.000000    12529.000000
mean    1594.647916      2.559582    111.389934      2.650970     6304.235808
std     1261.287104      1.077896    152.081061      0.976606     4162.305097
min      300.000000      1.000000      8.440000      1.000000      267.829813
25%     1116.000000      2.000000     49.000000      2.000000     4210.526316
50%     1300.000000      2.000000     70.000000      3.000000     5294.117647
75%     1700.000000      3.000000    115.000000      3.000000     6916.666667
max    52272.000000     16.000000   3600.000000     16.000000   176470.588235

In [78]:
data.shape

(12529, 7)

In [79]:
def remove_outliers_sqft(df): 
    df_output = pd.DataFrame() 
    for key,subdf in df.groupby('location'):
        m = np.mean(subdf.price_per_sqft)

        st = np.std(subdf.price_per_sqft)

        gen_df = subdf[(subdf .price_per_sqft > (m-st)) & (subdf.price_per_sqft <= (m+st))]
        df_output = pd.concat([df_output,gen_df],ignore_index= True)
    return df_output
data = remove_outliers_sqft(data)
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  10298.000000  10298.000000  10298.000000  10298.000000    10298.000000
mean    1508.562022      2.471742     91.303546      2.575063     5659.840869
std      880.740538      0.979457     86.349046      0.897618     2265.645796
min      300.000000      1.000000     10.000000      1.000000     1250.000000
25%     1110.000000      2.000000     49.000000      2.000000     4248.645408
50%     1286.000000      2.000000     67.000000      2.000000     5176.116129
75%     1650.000000      3.000000    100.000000      3.000000     6428.571429
max    30400.000000     16.000000   2200.000000     16.000000    24509.803922

In [80]:
def bhk_outlier_remover(df):
    exclude_indices = np.array([])
    for location, location_df in df.groupby('location'):
        bhk_stats ={}
        for bhk, bhk_df in location_df.groupby('bhk'):
            bhk_stats[bhk]={
                'mean': np.mean(bhk_df.price_per_sqft),
                'std': np.std(bhk_df.price_per_sqft),
                'count': bhk_df.shape[0]
            }
        for bhk, bhk_df in location_df.groupby('bhk'):
            stats = bhk_stats.get(bhk-1)
            if stats and stats['count']>5:
                exclude_indices = np.append(exclude_indices, bhk_df[bhk_df.price_per_sqft<(stats['mean'])].index.values)
    return df.drop(exclude_indices,axis='index')

In [81]:
data=bhk_outlier_remover(data)

In [82]:
data.shape

(7358, 7)

In [83]:
data

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,1st Block Jayanagar,4 BHK,2850.0,4.0,428.0,4,15017.543860
1,1st Block Jayanagar,3 BHK,1630.0,3.0,194.0,3,11901.840491
2,1st Block Jayanagar,3 BHK,1875.0,2.0,235.0,3,12533.333333
3,1st Block Jayanagar,3 BHK,1200.0,2.0,130.0,3,10833.333333
4,1st Block Jayanagar,2 BHK,1235.0,2.0,148.0,2,11983.805668
...,...,...,...,...,...,...,...
10289,other,2 BHK,1200.0,2.0,70.0,2,5833.333333
10290,other,1 BHK,1800.0,1.0,200.0,1,11111.111111
10293,other,2 BHK,1353.0,2.0,110.0,2,8130.081301
10294,other,1 Bedroom,812.0,1.0,26.0,1,3201.970443
10297,other,4 BHK,3600.0,5.0,400.0,4,11111.111111

In [84]:
data.drop(columns=['size','price_per_sqft'],inplace=True)

In [85]:
data.head()

              location  total_sqft  bath  price  bhk
0  1st Block Jayanagar      2850.0   4.0  428.0    4
1  1st Block Jayanagar      1630.0   3.0  194.0    3
2  1st Block Jayanagar      1875.0   2.0  235.0    3
3  1st Block Jayanagar      1200.0   2.0  130.0    3
4  1st Block Jayanagar      1235.0   2.0  148.0    2

In [86]:
data.to_csv("Cleaned_data.csv")

In [87]:
X=data.drop(columns=['price'])
y=data['price']

In [88]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [89]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [90]:
print(X_train.shape)
print(X_test.shape)

(5886, 4)
(1472, 4)

In [91]:
column_trans = make_column_transformer((OneHotEncoder(sparse_output=False),['location']),remainder='passthrough')

In [92]:
scaler= StandardScaler()

In [93]:
lr = LinearRegression()

In [94]:
pipe= make_pipeline(column_trans,scaler, lr)

In [95]:
pipe.fit(X_train,y_train)

c:\Users\Harshdeep Singh\Desktop\predict_house_price\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:1651: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [96]:
y_pred_lr = pipe.predict(X_test)

In [97]:
r2_score(y_test, y_pred_lr)

0.8226579056617656

APPLY LASSO REGRESSION

In [98]:
lasso = Lasso()

In [99]:
pipe = make_pipeline(column_trans, scaler, lasso)

In [100]:
pipe.fit(X_train,y_train)

c:\Users\Harshdeep Singh\Desktop\predict_house_price\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:1651: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [101]:
y_pred_lasso = pipe.predict(X_test)
r2_score(y_test,y_pred_lasso)

0.8132237308117184

In [102]:
ridge= Ridge()

In [103]:
pipe = make_pipeline(column_trans,scaler, ridge)

In [104]:
pipe.fit(X_train,y_train)

c:\Users\Harshdeep Singh\Desktop\predict_house_price\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:1651: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [105]:
y_pred_ridge = pipe.predict(X_test)
r2_score(y_test,y_pred_ridge)

0.8226702158162496

In [106]:
print("No regularization: ", r2_score(y_test,y_pred_lr))
print("Lasso: ", r2_score(y_test,y_pred_lasso))
print("Ridge:",r2_score(y_test,y_pred_ridge))

No regularization:  0.8226579056617656
Lasso:  0.8132237308117184
Ridge: 0.8226702158162496

In [107]:
import pickle

In [108]:
pickle.dump(pipe, open('RidgeModel.pkl','wb'))